// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZyphCare.EntityFramework.Units.HealthRecords;

#nullable disable

namespace ZyphCare.EntityFramework.Sqlite.Migrations.HealthRecordZyphCareDb
{
    [DbContext(typeof(HealthRecordZyphCareDbContext))]
    partial class HealthRecordZyphCareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ZyphCare.HealthRecords.Entities.HealthRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_HealthRecord_CreatedDate");

                    b.HasIndex("FileName")
                        .HasDatabaseName("IX_HealthRecord_FileName");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_HealthRecord_Type");

                    b.ToTable("HealthRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
