// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZyphCare.EntityFramework.Units.Users;

#nullable disable

namespace ZyphCare.EntityFramework.Sqlite.Migrations
{
    [DbContext(typeof(UserZyphCareDbContext))]
    [Migration("20250112192628_Initial_Create")]
    partial class Initial_Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ZyphCare.Users.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BloodType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Auth0Id")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Auth0Id");

                    b.HasIndex("BloodType")
                        .HasDatabaseName("IX_User_BloodType");

                    b.HasIndex("FirstName")
                        .HasDatabaseName("IX_User_FirstName");

                    b.HasIndex("LastName")
                        .HasDatabaseName("IX_User_LastName");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
